package ExcaptionHandling;

import java.io.FileNotFoundException;
import java.security.PublicKey;

public class Trycatchfinallythrowthrows {
	public static void main(String[] args) {
		
	
	name();
	}
//public static void main(String[] args)throws ArithmeticException,FileNotFoundException {
//	name();

//	public static void main(String[] args) throws ArithmeticException, FileNotFoundException {
//		name();
		/*System.err.println(10/0);
		System.err.println("statement1");
		try {

			System.out.println(10 / 0);
		} catch (ArithmeticException e) {
			// TODO: handle exception
		}
		System.out.println(10 / 2);

		System.out.println("Statement3");*/
//		Thread.sleep(2000);
//		try {
//			Thread.sleep(2000);
//		} catch (InterruptedException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
//		try {
//    System.out.println("main method started");
//		int a=100,  b=0, c;
//		c=a/b;
//		System.out.println(c);
//		}
//		catch (ArithmeticException e) {
////			System.out.println(e);
//			System.out.println(e.toString());
//			e.printStackTrace();
//		}
//		System.out.println("Hello");

//			System.out.println(10 / 0);
//		} catch (ArithmeticException e) {
//			e.printStackTrace();
//			System.err.println(e);
//			System.err.println(e.getMessage());
		
		/*try {
		System.out.println(10/0);
	}catch (Exception e) {
			e.printStackTrace();
		}
	} catch (ArithmeticException e) {
			e.printStackTrace();
		} */
//}catch(
//
//	FileFoundException e)
//	{
//		e.printStackTrace();
//	}
		
		
		
//		System.out.println(10/0);
//		throw new ArithmeticException();
//		System.out.println(10/5);
//		public static void name() {
//			System.out.println(10/0);
	
//		}
	public static void name() {
		
	
 try {
	System.out.println(10/0);
}catch (ArithmeticException e) {
	System.out.println("He");
}
	finally {
		
	}
 try {
	System.out.println(10/0);
}catch (Exception e) {
	System.out.println("He");
}
	finally {
		
	}


	
	}
}

